# Generated by Django 2.0.1 on 2018-01-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.TextField(blank=True, null=True)),
                ('field2', models.TextField(blank=True, null=True)),
                ('field3', models.TextField(blank=True, null=True)),
                ('field4', models.TextField(blank=True, null=True)),
                ('field5', models.TextField(blank=True, null=True)),
                ('field6', models.TextField(blank=True, null=True)),
                ('field7', models.TextField(blank=True, null=True)),
                ('field8', models.TextField(blank=True, null=True)),
                ('field9', models.TextField(blank=True, null=True)),
                ('field10', models.TextField(blank=True, null=True)),
                ('field11', models.TextField(blank=True, null=True)),
                ('field12', models.TextField(blank=True, null=True)),
                ('field13', models.TextField(blank=True, null=True)),
                ('field14', models.TextField(blank=True, null=True)),
                ('field15', models.TextField(blank=True, null=True)),
                ('field16', models.TextField(blank=True, null=True)),
                ('field17', models.TextField(blank=True, null=True)),
                ('field18', models.TextField(blank=True, null=True)),
                ('field19', models.TextField(blank=True, null=True)),
                ('field20', models.TextField(blank=True, null=True)),
                ('field21', models.TextField(blank=True, null=True)),
                ('field22', models.TextField(blank=True, null=True)),
                ('field23', models.TextField(blank=True, null=True)),
                ('field24', models.TextField(blank=True, null=True)),
                ('field25', models.TextField(blank=True, null=True)),
                ('field26', models.TextField(blank=True, null=True)),
                ('field27', models.TextField(blank=True, null=True)),
                ('field28', models.TextField(blank=True, null=True)),
                ('field29', models.TextField(blank=True, null=True)),
                ('field30', models.TextField(blank=True, null=True)),
                ('field31', models.TextField(blank=True, null=True)),
                ('field32', models.TextField(blank=True, null=True)),
                ('field33', models.TextField(blank=True, null=True)),
                ('field34', models.TextField(blank=True, null=True)),
                ('field35', models.TextField(blank=True, null=True)),
                ('field36', models.TextField(blank=True, null=True)),
                ('field37', models.TextField(blank=True, null=True)),
                ('field38', models.TextField(blank=True, null=True)),
                ('field39', models.TextField(blank=True, null=True)),
                ('field40', models.TextField(blank=True, null=True)),
                ('field41', models.TextField(blank=True, null=True)),
                ('field42', models.TextField(blank=True, null=True)),
                ('field43', models.TextField(blank=True, null=True)),
                ('field44', models.TextField(blank=True, null=True)),
                ('field45', models.TextField(blank=True, null=True)),
                ('field46', models.TextField(blank=True, null=True)),
                ('field47', models.TextField(blank=True, null=True)),
                ('field48', models.TextField(blank=True, null=True)),
                ('field49', models.TextField(blank=True, null=True)),
                ('field50', models.TextField(blank=True, null=True)),
                ('field51', models.TextField(blank=True, null=True)),
                ('field52', models.TextField(blank=True, null=True)),
                ('field53', models.TextField(blank=True, null=True)),
                ('field54', models.TextField(blank=True, null=True)),
                ('field55', models.TextField(blank=True, null=True)),
                ('field56', models.TextField(blank=True, null=True)),
                ('field57', models.TextField(blank=True, null=True)),
                ('field58', models.TextField(blank=True, null=True)),
                ('field59', models.TextField(blank=True, null=True)),
                ('field60', models.TextField(blank=True, null=True)),
                ('field61', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '상장법인목록',
                'managed': False,
            },
        ),
    ]
