# Generated by Django 2.0.1 on 2018-01-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
    ]
