# Generated by Django 2.0.1 on 2018-01-31 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20180131_1713'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stock',
            table=None,
        ),
    ]
