# Generated by Django 2.0.1 on 2018-01-31 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20180131_1714'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='stock_stock',
        ),
    ]
