# Generated by Django 2.0.1 on 2018-01-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20180131_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_stock',
            options={'managed': False},
        ),
    ]
