# Generated by Django 2.0.1 on 2018-01-31 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_auto_20180131_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SuiteName', models.CharField(max_length=255)),
                ('Test_Case', models.CharField(max_length=255)),
                ('FileName', models.CharField(max_length=255)),
                ('Total_Action', models.CharField(max_length=255)),
                ('Pass', models.CharField(max_length=255)),
                ('Fail', models.CharField(max_length=255)),
                ('Exe_Time', models.CharField(max_length=255)),
                ('Result', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Revo',
            },
        ),
    ]
