# Generated by Django 2.0.1 on 2018-01-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_revo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRevo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('suitename', models.CharField(db_column='SuiteName', max_length=255)),
                ('test_case', models.CharField(db_column='Test_Case', max_length=255)),
                ('filename', models.CharField(db_column='FileName', max_length=255)),
                ('total_action', models.CharField(db_column='Total_Action', max_length=255)),
                ('pass_field', models.CharField(db_column='Pass', max_length=255)),
                ('fail', models.CharField(db_column='Fail', max_length=255)),
                ('exe_time', models.CharField(db_column='Exe_Time', max_length=255)),
                ('result', models.CharField(db_column='Result', max_length=255)),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'stock_revo',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Revo',
        ),
    ]
