# Generated by Django 2.0.1 on 2018-01-31 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_stock2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
