# Generated by Django 2.0.1 on 2018-01-31 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_auto_20180131_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('company_name', models.TextField(blank=True, null=True)),
                ('index', models.TextField(blank=True, null=True)),
                ('sector', models.TextField(blank=True, null=True)),
                ('major_product', models.TextField(blank=True, null=True)),
                ('listed_day', models.TextField(blank=True, null=True)),
                ('account_day', models.TextField(blank=True, null=True)),
                ('representative', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('province', models.TextField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': '상장법인목록2',
                'managed': False,
            },
        ),
    ]
